name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck -y
    - name: Shellcheck
      run: shellcheck *.sh
